version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: cloud-kitchen-app
    environment:
      SPRING_APPLICATION_NAME: ${MYSQL_DATABASE_NAME}
      SPRING_DATASOURCE_URL: ${MYSQL_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATIONINMS: 3600000
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
