version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cloud-kitchen-db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - cloud-kitchen-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cloud_kitchen

  app:  
    depends_on:
      - mysql
    build:
      context: .
    restart: on-failure
    container_name: cloud-kitchen-app
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_NAME: cloud_kitchen
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloud_kitchen
      SPRING_DATASOURCE_USERNAME: chef
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      JWT_SECRET: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxNTcyNjMwNiwiaWF0IjoxNzE1NzI2MzA2fQ.ojPbMUdQcRrARltvnN6vx71PMHaq_sq9xD2xASfiRb4
      JWT_EXPIRATIONINMS: 3600000
    

volumes:
  cloud-kitchen-data:
